AllCops:
  TargetRubyVersion: 3.1.0

Style/TrivialAccessors:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false